/*
 * ImagePack.java
 *
 * Generated by BamFS - Bambalam J2ME filesystem
 *
 */
package com.hdc.mycasino.utilities;

import java.io.IOException;
import java.io.InputStream;

import android.R.string;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;

import com.danh.standard.Graphics;
import com.danh.standard.Image;
import com.hdc.mycasino.HDCGameMidlet;

public class ImagePack {
	public final static String MOUTH_PNG = "mouth";
	final static String ARROW_PNG = "arrow";
	final static String BACK_PLAY_PNG = "back_play";
	public final static String BIG_ARROW_PNG = "big_arrow";
	public final static String BOX_PNG = "box";
	public final static String BOX_FOCUS_PNG = "box_focus";
	final static String LOADING_PNG = "loading";
	final static String CARD_PNG = "card";
	final static String CARDUPSIDE_PNG = "cardupside";
	final static String CHAT_PNG = "chat";
	// public final static String CHECK_PNG = "check";
	final static String CLANS_PNG = "clans";
	public final static String COIN_ICON_PNG = "coin_icon";
	public final static String FRAMES_PNG = "frames";
	final static String HIEUUNG_PNG = "hieuung";
	final static String ICON_CARD_PNG = "icon_card";
	final static String ICON_CLAN_PNG = "icon_clan";
	public final static String ICON_GAME_PNG = "icon_game";
	public final static String ICON_MENU_PNG = "icon_menu";
	final static String INVITE_PNG = "invite";
	final static String ITEMS_PNG = "items";
	final static String LABAI_PNG = "labai";
	final static String MAIL_PNG = "mail";
	final static String MENUBAR_PNG = "menubar";
	final static String NHATNHIBABET_PNG = "nhatnhibabet";
	final static String ROOM_PNG = "room";
	final static String ROOM_STATUS_PNG = "room_status";
	final static String TABLE_FOUR_PLAYER_PNG = "table_four_player";
	public final static String TOURGUIDE_PNG = "tourguide";
	public final static String TOURGUIDE_EYE_PNG = "tourguide_eye";
	public final static String TOURGUIDE_HAND_PNG = "tourguide_hand";

	// TODO Login
	public final static String BACK_PNG = "back";
	public final static String BACK_2_PNG = "back_2";
	public final static String LOGO_PNG = "logo";
	public final static String LIGHT_1_PNG = "light_1";
	public final static String LIGHT_2_PNG = "light_2";
	public final static String BULB_PNG = "bong_den"; // bóng đèn

	// TODO TEXT FIELD
	public final static String TEXTFIELD_DISABLE_PNG = "textfield/textfield_disable";
	public final static String TEXTFIELD_ENABLE_PNG = "textfield/textfield_enable";
	public final static String TEXTFIELD_ICON_EDIT_PNG = "textfield/icon_edit";

	// background check ghi nhớ thông tin
	public final static String REMEMBERINFO_BG_PNG = "rememberinfo_bg";
	// frame check ghi nhớ thông tin
	public final static String REMEMBERINFO_CHECK_PNG = "rememberinfo_check";

	// TODO Menu
	public final static String MENU_DISABLE_PNG = "menu/menu_disable";
	public final static String MENU_ENABLE_PNG = "menu/menu_enable";
	public final static String MENU_BG_PNG = "menu/menu_bg";
	public final static String MENU_ICON_PNG = "menu/menu_icon";
	public final static String MENU_LIST_ICON_ENABLE_PNG = "menu/menu_list_icon_enable";
	public final static String MENU_LIST_ICON_DISABLE_PNG = "menu/menu_list_icon_disable";
	// NEW
	public final static String MENU_BG_GAME_PNG = "menu/menu_bg_game";
	public final static String MENU_BUTTON_PNG = "menu/menu_button";
	public final static String MENU_ICON_MENU_GAME_PNG = "menu/icon_menu_game";
	public final static String MENU_CONTEXT_MENU_1_PNG = "menu/context_menu_1";
	public final static String MENU_CONTEXT_MENU_2_PNG = "menu/context_menu_2";
	public final static String MENU_CONTEXT_MENU_3_PNG = "menu/context_menu_3";
	public final static String MENU_CONTEXT_HIGHLIGHT_PNG = "menu/context_menu_highlight";
	public final static String MENU_CONTEXT_CLOSE_PNG = "menu/context_menu_close";
	public final static String MENU_BUTTON_BACK_PNG = "menu/button_back";

	// TODO Button
	public final static String BUTTON_LOGIN = "button/button_Login";
	public final static String BUTTON_HIGHLIGHT_BUTTON = "button/highlight_button";
	// Hight Light Effect 1
	public final static String HIGHT_LIGHT_1_PNG = "button/hightlight_1";
	// Hight Light Effect 2
	public final static String HIGHT_LIGHT_2_PNG = "button/hightlight_2";
	// Hight Light Effect 3
	public final static String HIGHT_LIGHT_3_PNG = "button/hightlight_3";

	// TODO Popup
	public final static String POPUP_BUTTON_PNG = "popup/button";
	public final static String POPUP_LINE_PNG = "popup/line";
	public final static String POPUP_LINE_1_PNG = "popup/line_1";
	public final static String POPUP_PANEL_PNG = "popup/panel";
	public final static String POPUP_ARROW_PNG = "popup/arrow";
	public final static String POPUP_ARROW_ROTATE_PNG = "popup/arrow_rotate";
	public final static String POPUP_POP_PNG = "popup/pop";

	// TODO Header
	public final static String HEADER_BG_PNG = "header/bg";
	public final static String HEADER_DINA_BG_PNG = "header/dina_bg";
	public final static String HEADER_ICON_GOLD_PNG = "header/icon_dina_gold";
	public final static String HEADER_MSG_ICON_PNG = "header/msg_icon";
	//NEW
	public final static String HEADER_TOP_PNG = "header/top";
	public final static String HEADER_BOTTOM_PNG = "header/bottom";
	public final static String HEADER_CHECK_PNG = "header/check";
	
	
	// TODO Effect Icon
	public final static String EFFECT_ICON_HIGHTLIGHT_PNG = "effect_icon/hight_light_icon";
	public final static String EFFECT_ICON_LARGE_PNG = "effect_icon/icon_large";
	public final static String EFFECT_ICON_MEDIUM_PNG = "effect_icon/icon_medium";
	public final static String EFFECT_ICON_SMALL_1_PNG = "effect_icon/icon_small_1";
	public final static String EFFECT_ICON_SMALL_2_PNG = "effect_icon/icon_small_2";
	public final static String EFFECT_ICON_TEXT_MENU_PNG = "effect_icon/text_menu";
	public final static String EFFECT_ICON_SHADOW_PNG = "effect_icon/icon_shadow";
	public final static String EFFECT_ICON_TINNHAN_PNG = "effect_icon/icon_tinnhan";

	// TODO list screen
	public final static String LIST_SCREEN_PANEL = "list_screen/panel";
	public final static String LIST_SCREEN_HIGHT_LIGHT = "list_screen/hight_light_v2";
	public final static String LIST_SCREEN_SCROLL_BAR = "list_screen/scroll_bar";
	public final static String LIST_SCREEN_SCROLL_BAR_NGANG = "list_screen/scroll_bar_ngang";
	// TODO scroll
	public final static String SCROLL_BAR_PNG = "list_screen/scroll_bar";
	public final static String SCROLL_PANEL_PNG = "list_screen/scroll_panel";

	// TODO tabs
	public final static String TABS_HIGHT_LIGHT_ROW = "tabs/high_light_row_v2";
	public final static String TABS_1_0_PNG = "tabs/tabs_1_0";
	public final static String TABS_2_0_PNG = "tabs/tabs_2_0";
	public final static String TABS_2_1_PNG = "tabs/tabs_2_1";
	public final static String TABS_3_0_PNG = "tabs/tabs_3_0";
	public final static String TABS_3_1_PNG = "tabs/tabs_3_1";
	public final static String TABS_3_2_PNG = "tabs/tabs_3_2";
	public final static String TABS_4_0_PNG = "tabs/tabs_4_0";
	public final static String TABS_4_1_PNG = "tabs/tabs_4_1";
	public final static String TABS_4_2_PNG = "tabs/tabs_4_2";
	public final static String TABS_4_3_PNG = "tabs/tabs_4_3";

	// TODO avatar
	public final static String AVATAR_ICON_BLUE_PNG = "avatar/icon_blue";
	public final static String AVATAR_ICON_RED_PNG = "avatar/icon_red";
	public final static String AVATAR_ICON_YELLOW_PNG = "avatar/icon_yellow";
	public final static String AVATAR_KHUNG_AVATAR_PNG = "avatar/khung_avatar";
	public final static String AVATAR_KHUNG_AVATAR_HIGH_LIGHT_PNG = "avatar/khung_avatar_high_light";
	public final static String AVATAR_ICON_AVATAR_PNG = "avatar/icon_avatar";
	// NEW
	public final static String AVATAR_ICON_AVATAR_1_PNG = "avatar/icon_avatar_1";

	// TODO mail
	public final static String MAIL_ICON_HOMTHU = "mail/icon_homthu";

	// TODO vật phẩm
	public final static String VATPHAM_ICON_PNG = "vatpham/icon_vatpham";

	// TODO gia tộc
	public final static String GIATOC_ICON_PNG = "giatoc/icon_giatoc";
	public final static String GIATOC_ICON_THANHLAP = "giatoc/icon_thanhlap";
	public final static String GIATOC_ICON_HIGH_LIGHT = "giatoc/hight_light_icon";
	public final static String GIATOC_STAR = "giatoc/star";

	// TODO chat
	public final static String CHAT_ICON_GUI_PNG = "chat/icon_gui";
	public final static String CHAT_MAN_PNG = "chat/man";
	public final static String CHAT_PANEL_PNG = "chat/panel";
	public final static String CHAT_WHITE_POPUP_PNG = "chat/white_popup";

	// TODO room
	public final static String ROOM_ICON_GIATOC_PNG = "room/icon_giatoc";
	public final static String ROOM_ICON_PHONG_PNG = "room/icon_phong";
	public final static String ROOM_ICON_TABLE_PNG = "room/icon_table";
	public final static String ROOM_ICON_USER_PNG = "room/icon_user";
	//NEW 
	public final static String ROOM_ICON_ROOM_PNG = "room/icon_room";

	// TODO Tiến lên
	public final static String TIENLEN_TABLE_PNG = "tienlen/table";
	public final static String TIENLEN_PANEL_INFO_PNG = "tienlen/panel_info";
	public final static String TIENLEN_STAR_PNG = "tienlen/star";
	public final static String TIENLEN_READY_PNG = "tienlen/ready";
	public final static String TIENLEN_CHAT_PNG = "tienlen/chat";
	public final static String TIENLEN_BUTTON_PNG = "tienlen/button";
	public final static String TIENLEN_ICON_START_READY_1_PNG = "tienlen/icon_start_ready_1";
	public final static String TIENLEN_ICON_START_READY_2_PNG = "tienlen/icon_start_ready_2";
	public final static String TIENLEN_CARD_BACK_PNG = "cards/card_back";
	public final static String TIENLEN_CARD_BACK2_PNG = "cards/card_back2";
	public final static String TIENLEN_CARD_TIME_BG_PNG = "tienlen/time_bg";
	public final static String TIENLEN_CARD_TIME_LINE_PNG = "tienlen/time_line";
	public final static String TIENLEN_CARD_NUMBER_PNG = "tienlen/number";
	// new card tien len
	public final static String BACKLIGHT_PNG = "cards/backLight";
	public final static String TIENLEN_ALLCARDS = "tienlen/AllCard";
	// new Tiến lên
	public final static String TIENLEN_USER_PNG = "tienlen/user";
	public final static String TIENLEN_KHUNG_USER_PNG = "tienlen/khung_user";
	public final static String TIENLEN_ICON_USER_PNG = "tienlen/icon_user";
	public final static String TIENLEN_CARD_TIME_OUT_LIGHT_PNG = "tienlen/time_out_light";
	public final static String TIENLEN_LINE_BUTTON_PNG = "tienlen/line_button";
	public final static String TIENLEN_TITLE_PNG = "tienlen/title";

	// TODO Icon Win
	public final static String WIN_NHAT_PNG = "win/nhat";
	public final static String WIN_NHI_PNG = "win/nhi";
	public final static String WIN_BA_PNG = "win/ba";
	public final static String WIN_BET_PNG = "win/bet";
	public final static String WIN_THUI_13_LA_PNG = "win/thui_13_la";
	public final static String WIN_CHAT_DE_PNG = "win/chat_de";
	public final static String WIN_CHAT_HEO_PNG = "win/chat_heo";
	public final static String WIN_CHIP_PNG = "win/chip";
	public final static String WIN_BATAY_PNG = "win/batay";
	public final static String WIN_XAM_PNG = "win/xam";
	public final static String WIN_THANG_PNG = "win/thang";
	public final static String WIN_THUA_PNG = "win/thua";
	// NEW
	public final static String WIN_ICON_WIN_PNG = "win/icon_win";
	public final static String WIN_HIGH_LIGHT_WIN_PNG = "win/high_light_win";
	public final static String WIN_TO_PNG = "win/to";
	public final static String WIN_TO_THEM_PNG = "win/to_them";
	public final static String WIN_THEO_PNG = "win/theo";
	public final static String WIN_UP_BO_PNG = "win/up_bo";
	

	// TODO Bài cào
	public final static String BAICAO_TABLE_PNG = "baicao/table";
	public final static String BAICAO_DIEM_PNG = "baicao/diem";
	public final static String BAICAO_NUMBER_PNG = "baicao/number";
	public final static String BAICAO_ICON_HAND_PNG = "baicao/icon_hand";

	// TODO demo
	public final static String DEMO = "abc";

	// TODO Xì tố
	public final static String XITO_TABLE_PNG = "xito/table";
	public final static String XITO_BOX_PNG = "xito/box";
	public final static String XITO_TEXT_PNG = "xito/text";

	//TODO phỏm
	public final static String PHOM_TABLE_PNG = "phom/table";
	public final static String PHOM_HIGHT_LIGHT_CHONBAI_PNG = "phom/hight_light_chonbai";	
	public final static String PHOM_BOCBAI_PNG = "phom/bocbai";
	public final static String PHOM_ANBAI_PNG = "phom/anbai";
	public final static String PHOM_U_PNG = "phom/u";
	public final static String PHOM_DEN_PNG = "phom/u_den";
	
	//TODO HIGH LIGHT CARD
	public final static String CARD_HIGH_LIGHT = "cards/high_light_card";
	public final static String CARD_HIGH_LIGHT_1 = "cards/high_light_card_1";
	
	//TODO fly star
	public final static String FLY_STAR = "star_effects";
	
	public static InputStream createInputStream(String fileName){
		try {
			return HDCGameMidlet.assets.open(fileName);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			return null;
		}
	}
	
	public static Bitmap createBitmap(String fileName){
		Bitmap bitmap = null;
		InputStream in = createInputStream(fileName);
		try {
			bitmap = BitmapFactory.decodeStream(in);
			if (bitmap == null)
				throw new RuntimeException("Couldn't load bitmap from asset '" + fileName + "'");
			else if (HDCGameMidlet.scale != 1) {
				if (!fileName.contains("server")) {
					bitmap = Graphics.BitmapResize(bitmap, bitmap.getWidth() / HDCGameMidlet.scale,
							bitmap.getHeight() / HDCGameMidlet.scale);
					// else
					// bitmap = Graphics.BitmapResize(bitmap,
					// (float) bitmap.getWidth() * 3 / 4,
					// (float) bitmap.getHeight() * 3 / 4);

				}
			}/*
			 * else if (HDCGameMidlet.instance.scale == 1) { if (GameCanvas.w <
			 * 800) bitmap = Graphics.BitmapResize(bitmap, GameCanvas.w
			 * bitmap.getWidth() / 800, bitmap.getHeight()); }
			 */

//		} catch (IOException e) {
//			throw new RuntimeException("Couldn't load bitmap from asset '" + fileName + "'");
		} finally {
			if (in != null) {
				try {
					in.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}
		return bitmap;
	}
	
	public static Image createImage(String fileName) {
		fileName += ".png";
		return new Image(createBitmap(fileName));
	}

	// TODO load image and scale
	public static Image createImage(String fileName, float scale) {

		InputStream in = null;
		Bitmap bitmap = null;
		try {

			fileName += ".png";
			in = HDCGameMidlet.assets.open(fileName);
			bitmap = BitmapFactory.decodeStream(in);
			if (bitmap == null)
				throw new RuntimeException("Couldn't load bitmap from asset '" + fileName + "'");
			// else if (HDCGameMidlet.instance.scale != 1) {
			// if (!fileName.contains("server")) {
			// bitmap = Graphics
			// .BitmapResize(bitmap, bitmap.getWidth() == 1 ? 1
			// : bitmap.getWidth() >> 1, bitmap
			// .getHeight() >> 1);
			// }
			// }

			float newWidth = bitmap.getWidth() * scale;
			float newHeight = bitmap.getHeight() * scale;

			bitmap = Graphics.BitmapResize(bitmap, newWidth, newHeight);

		} catch (IOException e) {
			throw new RuntimeException("Couldn't load bitmap from asset '" + fileName + "'");
		} finally {
			if (in != null) {
				try {
					in.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}

		return new Image(bitmap);
	}
}
